-- Poblamiento consistente para PhotoSport
USE photosport;

INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Camila', 'Ocasio', 'camila.ocasio1@mail.com', '1043321819', 'cliente1123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Tomás', 'Quintanilla', 'tomás.quintanilla2@mail.com', '6001338908', 'cliente2123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Yolanda', 'Villaseñor', 'yolanda.villaseñor3@mail.com', '3863794026', 'cliente3123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Ángela', 'Montes', 'ángela.montes4@mail.com', '5423511615', 'cliente4123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Perla', 'Nieves', 'perla.nieves5@mail.com', '5940781618', 'cliente5123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Raquel', 'Matos', 'raquel.matos6@mail.com', '4959310341', 'cliente6123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Ilse', 'Concepción', 'ilse.concepción7@mail.com', '3164752553', 'cliente7123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('José Eduardo', 'Quiñónez', 'joséeduardo.quiñónez8@mail.com', '4192832764', 'cliente8123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Leticia', 'Gallardo', 'leticia.gallardo9@mail.com', '8350305641', 'cliente9123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Claudio', 'Dueñas', 'claudio.dueñas10@mail.com', '3953767242', 'cliente10123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Daniel', 'Ozuna', 'daniel.ozuna11@mail.com', '3884969653', 'cliente11123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Aida', 'Delgadillo', 'aida.delgadillo12@mail.com', '2871012269', 'cliente12123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Elias', 'Meraz', 'elias.meraz13@mail.com', '1669784801', 'cliente13123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Manuel', 'Navarro', 'manuel.navarro14@mail.com', '8451462704', 'cliente14123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Mauricio', 'Cruz', 'mauricio.cruz15@mail.com', '8281489325', 'cliente15123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Reina', 'Santacruz', 'reina.santacruz16@mail.com', '2880957015', 'cliente16123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Jaime', 'Robledo', 'jaime.robledo17@mail.com', '4303911718', 'cliente17123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Oswaldo', 'Amador', 'oswaldo.amador18@mail.com', '2278248963', 'cliente18123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Helena', 'Portillo', 'helena.portillo19@mail.com', '8346578713', 'cliente19123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('María Cristina', 'Velasco', 'maríacristina.velasco20@mail.com', '3150983930', 'cliente20123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Alejandro', 'Echeverría', 'alejandro.echeverría21@mail.com', '1031051834', 'cliente21123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Perla', 'Leyva', 'perla.leyva22@mail.com', '7382997376', 'cliente22123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Silvano', 'Laboy', 'silvano.laboy23@mail.com', '3116566701', 'cliente23123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Lorena', 'Tovar', 'lorena.tovar24@mail.com', '0651333872', 'cliente24123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Clemente', 'Lucio', 'clemente.lucio25@mail.com', '6247317810', 'cliente25123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Cornelio', 'Ocasio', 'cornelio.ocasio26@mail.com', '8013267736', 'cliente26123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Teresa', 'Carrera', 'teresa.carrera27@mail.com', '0260647468', 'cliente27123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Gerardo', 'Ballesteros', 'gerardo.ballesteros28@mail.com', '7234309805', 'cliente28123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Carla', 'Tamayo', 'carla.tamayo29@mail.com', '0097882081', 'cliente29123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Israel', 'Reséndez', 'israel.reséndez30@mail.com', '2191361939', 'cliente30123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Patricio', 'Solorzano', 'patricio.solorzano31@mail.com', '9091699854', 'cliente31123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Concepción', 'Centeno', 'concepción.centeno32@mail.com', '3534624751', 'cliente32123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Evelio', 'Razo', 'evelio.razo33@mail.com', '0799118384', 'cliente33123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Cristobal', 'de la O', 'cristobal.delao34@mail.com', '2513542784', 'cliente34123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Andrés', 'Pacheco', 'andrés.pacheco35@mail.com', '9808412411', 'cliente35123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Adriana', 'Soliz', 'adriana.soliz36@mail.com', '8244935348', 'cliente36123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Marcela', 'Mejía', 'marcela.mejía37@mail.com', '7401640052', 'cliente37123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Miguel Ángel', 'Pulido', 'miguelángel.pulido38@mail.com', '4278680112', 'cliente38123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Silvia', 'Valles', 'silvia.valles39@mail.com', '8059826204', 'cliente39123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Zeferino', 'Ortega', 'zeferino.ortega40@mail.com', '5053315869', 'cliente40123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Gabriela', 'Noriega', 'gabriela.noriega41@mail.com', '2322602563', 'cliente41123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Luis', 'Vera', 'luis.vera42@mail.com', '4216073375', 'cliente42123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Espartaco', 'Zedillo', 'espartaco.zedillo43@mail.com', '4330365414', 'cliente43123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Adela', 'Vega', 'adela.vega44@mail.com', '5868501429', 'cliente44123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Irma', 'Franco', 'irma.franco45@mail.com', '4019655698', 'cliente45123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Andrea', 'Badillo', 'andrea.badillo46@mail.com', '1693406088', 'cliente46123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Oswaldo', 'Padrón', 'oswaldo.padrón47@mail.com', '3561595148', 'cliente47123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Karina', 'Elizondo', 'karina.elizondo48@mail.com', '4656482366', 'cliente48123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('José María', 'Tapia', 'josémaría.tapia49@mail.com', '2994680443', 'cliente49123');
INSERT INTO cliente (nombre, apellido, correo, telefono, contrasena) VALUES ('Emilio', 'Coronado', 'emilio.coronado50@mail.com', '6995777387', 'cliente50123');

INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('María José', 'Saucedo', 'fotografo1@photosport.com', '2148951343', 'foto1secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Olga', 'Montañez', 'fotografo2@photosport.com', '3200379176', 'foto2secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Pablo', 'Alcala', 'fotografo3@photosport.com', '9367632016', 'foto3secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Zacarías', 'de la O', 'fotografo4@photosport.com', '3287083172', 'foto4secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Reina', 'Pantoja', 'fotografo5@photosport.com', '7889579868', 'foto5secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Cecilia', 'Aguirre', 'fotografo6@photosport.com', '7277434873', 'foto6secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Luis Miguel', 'Castellanos', 'fotografo7@photosport.com', '4714345581', 'foto7secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Jaime', 'Hidalgo', 'fotografo8@photosport.com', '2236231665', 'foto8secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Gabriela', 'Peralta', 'fotografo9@photosport.com', '8760366909', 'foto9secure');
INSERT INTO fotografo (nombre, apellido, correo, telefono, contrasena) VALUES ('Tomás', 'Barreto', 'fotografo10@photosport.com', '6705466889', 'foto10secure');

INSERT INTO evento (nombre, deporte, fecha_ini, fecha_fin, lugar, organizador) VALUES ('Maratón Puebla', 0, '2026-06-10', '2026-06-10', 'Puebla', 'Gobierno Puebla');
INSERT INTO evento (nombre, deporte, fecha_ini, fecha_fin, lugar, organizador) VALUES ('Triatlón Atlixco', 1, '2026-07-20', '2026-07-20', 'Atlixco', 'TriMX');
INSERT INTO evento (nombre, deporte, fecha_ini, fecha_fin, lugar, organizador) VALUES ('Copa Universitaria', 2, '2026-08-15', '2026-08-17', 'UDLAP', 'Universidades MX');
INSERT INTO evento (nombre, deporte, fecha_ini, fecha_fin, lugar, organizador) VALUES ('Carrera Nocturna', 0, '2026-09-05', '2026-09-05', 'Puebla', 'ITESM Puebla');
INSERT INTO evento (nombre, deporte, fecha_ini, fecha_fin, lugar, organizador) VALUES ('Torneo Estatal', 1, '2026-10-11', '2026-10-15', 'Cholula', 'Liga Estatal');

INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (1, 2);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (1, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (2, 1);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (2, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (2, 5);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (3, 1);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (3, 3);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (3, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (3, 5);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (4, 1);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (4, 2);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (4, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (4, 5);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (5, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (6, 2);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (6, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (7, 3);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (8, 2);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (8, 3);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (8, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (8, 5);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (9, 2);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (9, 3);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (9, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (10, 1);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (10, 4);
INSERT INTO fotografo_evento (id_fotografo, id_evento) VALUES (10, 5);

INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (1, 'Basico', 1200, 'Cobertura completa', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (2, 'Basico', 500, 'Cobertura parcial', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (3, 'Basico', 800, 'Cobertura parcial', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (3, 'Premium', 2500, 'Cobertura completa', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (4, 'Basico', 800, 'Fotos de premiación', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (4, 'Premium', 500, 'Cobertura completa', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (5, 'Basico', 1200, 'Fotos ilimitadas', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (5, 'Premium', 800, 'Cobertura parcial', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (5, 'VIP', 800, 'Fotos ilimitadas', 'Paquete VIP para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (5, 'Ultra', 500, 'Cobertura parcial', 'Paquete Ultra para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (6, 'Basico', 2500, 'Fotos de premiación', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (6, 'Premium', 1800, 'Cobertura completa', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (6, 'VIP', 500, 'Cobertura completa', 'Paquete VIP para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (7, 'Basico', 1200, 'Cobertura parcial', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (8, 'Basico', 1200, 'Fotos de premiación', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (9, 'Basico', 500, 'Fotos ilimitadas', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (9, 'Premium', 500, 'Fotos de premiación', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (9, 'VIP', 1800, 'Cobertura parcial', 'Paquete VIP para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (10, 'Basico', 1200, 'Fotos de premiación', 'Paquete Basico para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (10, 'Premium', 800, 'Fotos de premiación', 'Paquete Premium para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (10, 'VIP', 800, 'Fotos ilimitadas', 'Paquete VIP para eventos deportivos');
INSERT INTO paquete_fotografico (id_fotografo, nombre, precio, cobertura, descripcion) VALUES (10, 'Ultra', 2500, 'Fotos de premiación', 'Paquete Ultra para eventos deportivos');

INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (1, 14, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (1, 8, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (2, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (2, 20, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (3, 1, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (3, 6, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (4, 9, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (4, 20, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (5, 1, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (5, 8, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (5, 18, 2, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (6, 21, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (6, 15, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (7, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (7, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (8, 12, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (8, 17, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (8, 18, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (9, 15, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (9, 9, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (9, 7, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (10, 18, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (10, 7, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (10, 16, 3, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (11, 17, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (11, 4, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (11, 8, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (12, 1, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (12, 2, 1, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (13, 5, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (13, 1, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (14, 15, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (14, 2, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (15, 3, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (16, 19, 5, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (17, 5, 2, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (18, 3, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (18, 18, 3, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (19, 20, 1, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (19, 13, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (19, 10, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (20, 20, 1, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (20, 4, 3, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (20, 7, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (21, 6, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (22, 3, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (22, 14, 3, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (22, 20, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (23, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (24, 15, 2, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (24, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (25, 22, 1, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (25, 4, 3, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (25, 5, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (26, 2, 1, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (27, 19, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (27, 4, 5, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (27, 10, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (28, 18, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (28, 3, 1, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (28, 11, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (29, 8, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (30, 19, 1, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (30, 16, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (31, 9, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (31, 14, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (32, 12, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (32, 11, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (33, 14, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (33, 22, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (34, 15, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (35, 11, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (35, 17, 2, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (36, 15, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (36, 7, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (36, 16, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (37, 7, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (38, 10, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (39, 4, 1, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (39, 20, 1, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (40, 10, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (41, 3, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (41, 15, 2, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (42, 16, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (43, 9, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (43, 16, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (43, 18, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (44, 20, 5, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (45, 3, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (46, 17, 3, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (46, 10, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (47, 22, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (47, 15, 5, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (47, 11, 4, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (48, 7, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (48, 13, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (49, 11, 4, 1);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (50, 13, 2, 0);
INSERT INTO compra (id_cliente, id_paquete, id_evento, entregado) VALUES (50, 2, 1, 1);